const localeSeparators = {
	'DE-AT': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-AU': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'FR-BE': { dateTimeSeparator: ', ', dateRangeSeparator: ' au ', timeRangeSeparator: ' à ' },
	'NL-BE': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-CA': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'FR-CA': { dateTimeSeparator: ', ', dateRangeSeparator: ' au ', timeRangeSeparator: ' à ' },
	'DE-CH': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-CH': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'FR-CH': { dateTimeSeparator: ', ', dateRangeSeparator: ' au ', timeRangeSeparator: ' à ' },
	'IT-CH': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'CS-CZ': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'DE-DE': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'DA-DK': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-ES': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'ES-ES': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'GL-ES': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'CA-ES': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EU-ES': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'FI-FI': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'FR-FR': { dateTimeSeparator: ', ', dateRangeSeparator: ' au ', timeRangeSeparator: ' à ' },
	'EN-GB': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'HR-HR': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'HU-HU': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-IE': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-IN': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'IT-IT': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-JP': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'JA-JP': { dateTimeSeparator: '、', dateRangeSeparator: 'から', timeRangeSeparator: 'から' },
	'EN-KR': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'KO-KR': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-NL': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'NL-NL': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'NO-NO': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'PL-PL': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-PT': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'PT-PT': { dateTimeSeparator: ', às ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'RO-RO': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'SR-RS': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'SV-SE': { dateTimeSeparator: ' kl. ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'SL-SI': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'SK-SK': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-US': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-BE': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-CZ': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-AT': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-SE': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-FI': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'ES-US': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' },
	'EN-DE': { dateTimeSeparator: ', ', dateRangeSeparator: '–', timeRangeSeparator: '–' }
};

module.exports = localeSeparators;